### ISSUE TITLE
CaptureExample4 fails with NullPointerException

### ISSUE THREAD

**Issue by unknown-spirit** [slytechs-repos/jnetpcap-examples#2]
Hi,
When trying to run Example4 I encounter a premature termination with the following message
`Exception in thread "main" java.lang.NullPointerException:`
`Cannot invoke "com.slytechs.jnet.runtime.internal.json.JsonObject.getJsonObject(String)" because "jsonConf" is null`

Does this mean that I need additional libraries?
Thanks for support

**Comment by slytechs-repos** [comment]
This is a bug in the library. Its actually very minor and is caused by invalid resource file for one of the protocols, my guess would be "http" or "html" since there were some fields added to the header definition just to get some basics and the corresponding json resource file was not properly updated to each added header field.

Here is the good news, the resource files are only used to load "meta" information about each header for the "PacketFormat" class. So if you just not call `http.toString()` or `html.toString()`, sorry can't tell from the error which one it is, it will not throw that error.

This has already been fixed in the dev branch, and also a new `Header.toString(Detail, PacketFormat)` call has been added, which allows `http.toString(Detail.LOW, null)` which disables currently set packet formatter and defaults to pain packet formater (which is a one liner) and does not printout any json resources involved.

I'm working on getting a new much improved release done this week with IPF reassembly and lots of new features.

**Comment by unknown-spirit** [comment]
Unfortunately, it only works if I don't print out any packet data at all.
Thanks for the info, though.

**Comment by slytechs-repos** [comment]
I will get a fix out for this week. We have, its a MUST, to make sure all the examples work correctly.
